from typing import Annotated

from langgraph.graph import MessagesState
from typing_extensions import TypedDict


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    # Londres deterministic market-structure context
    analysis_mode: Annotated[str, "Londres analysis horizon: SWING or DAILY_SWING"]
    weekly_profile_state: Annotated[
        dict, "Deterministic weekly profile, day type, expected OLHC/OHLC delivery, and status"
    ]
    htf_order_flow_state: Annotated[
        dict, "Deterministic multi-timeframe IOF/IOFC control map"
    ]
    daily_profile_state: Annotated[
        dict, "Deterministic fixed-UTC-4 Daily OLHC/OHLC profile and phase"
    ]
    h4_profile_state: Annotated[
        dict, "Deterministic H4 profile including 18/22/02/06/10/14 candles and 06:00 driver"
    ]
    profile_stack_state: Annotated[
        dict, "Combined Weekly -> Daily -> H4 deterministic profile inheritance"
    ]
    time_price_state: Annotated[
        dict, "Deterministic opening-price and ONS map including EQ and projection levels"
    ]
    liquidity_state: Annotated[
        dict,
        "Deterministic BSL/SSL, IRL/ERL, raids, protected liquidity, and active draw map",
    ]
    smt_state: Annotated[
        dict,
        "Deterministic SMT divergence with polarity normalization and CSD+IOF validation state",
    ]
    londres_context_state: Annotated[
        dict,
        "Combined Weekly -> Daily -> H4 -> Time & Price -> Liquidity -> SMT deterministic context",
    ]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
